/*
 * The MIT License
 *
 * Copyright 2018 Acerbis Gianluca <www.acerbisgianluca.com>.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.acerbisgianluca.countdown;

import java.util.Observable;
import java.util.Observer;
import javax.swing.ImageIcon;

/**
 *
 * @author Acerbis Gianluca <www.acerbisgianluca.com>
 */
public class Graphic extends javax.swing.JFrame implements Observer {
    
    private Countdown cd;
    
    /**
     * Creates new form Main
     */
    public Graphic() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("img/timer.png")).getImage());
        cd = new Countdown(panelCountdown, lblTimer, txtTimer);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCountdown = new javax.swing.JPanel();
        lblTimer = new javax.swing.JLabel();
        lblSet = new javax.swing.JLabel();
        txtTimer = new javax.swing.JFormattedTextField();
        btnStartStop = new javax.swing.JToggleButton();
        checkSave = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        txtEndText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Countdown for streaming");
        setName("main"); // NOI18N

        lblTimer.setFont(new java.awt.Font("Impact", 1, 70)); // NOI18N
        lblTimer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTimer.setText("00:00:00");
        lblTimer.setToolTipText("");
        lblTimer.setAlignmentX(100.0F);
        lblTimer.setAlignmentY(0.0F);
        lblTimer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblTimer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblSet.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblSet.setText("Type end time (hh:mm:ss)");

        try {
            txtTimer.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTimer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTimer.setText("00:00:00  ");
        txtTimer.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        btnStartStop.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnStartStop.setText("Start");
        btnStartStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartStopActionPerformed(evt);
            }
        });

        checkSave.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        checkSave.setText("Save on file (it will be in the same folder of this app)");
        checkSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSaveActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("Type end text");

        txtEndText.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtEndText.setEnabled(false);

        javax.swing.GroupLayout panelCountdownLayout = new javax.swing.GroupLayout(panelCountdown);
        panelCountdown.setLayout(panelCountdownLayout);
        panelCountdownLayout.setHorizontalGroup(
            panelCountdownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCountdownLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCountdownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelCountdownLayout.createSequentialGroup()
                        .addComponent(lblSet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimer, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnStartStop, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(panelCountdownLayout.createSequentialGroup()
                        .addGroup(panelCountdownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(checkSave)
                            .addGroup(panelCountdownLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEndText)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelCountdownLayout.setVerticalGroup(
            panelCountdownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCountdownLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTimer)
                .addGap(18, 18, 18)
                .addGroup(panelCountdownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSet)
                    .addComponent(btnStartStop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCountdownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEndText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCountdown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCountdown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void checkSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSaveActionPerformed
        if(checkSave.isSelected())
            txtEndText.setEnabled(true);
        else
            txtEndText.setEnabled(false);
    }//GEN-LAST:event_checkSaveActionPerformed

    private void btnStartStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartStopActionPerformed
        if(btnStartStop.isSelected()){
            txtEndText.setEnabled(false);
            txtTimer.setEnabled(false);
            checkSave.setEnabled(false);
            
            String sTimer = txtTimer.getText();
            cd.setsTimer(sTimer);
            boolean save = checkSave.isSelected();
            cd.setSave(save);
            String endText = txtEndText.getText();
            cd.setEndText(endText);
            
            cd.start();
            
            btnStartStop.setText("Stop");
        }
        else {
            if(!cd.isFinished())
                cd.stop();
            btnStartStop.setText("Start");
            txtTimer.setEnabled(true);
            checkSave.setEnabled(true);
            if(checkSave.isSelected())
                txtEndText.setEnabled(true);
            else
                txtEndText.setEnabled(false);
        }
    }//GEN-LAST:event_btnStartStopActionPerformed

    @Override
    public void update(Observable o, Object arg) {
        btnStartStop.doClick();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Graphic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Graphic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Graphic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Graphic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Graphic g = new Graphic();
                g.setVisible(true);
                g.cd.addObserver(g);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnStartStop;
    private javax.swing.JCheckBox checkSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblSet;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JPanel panelCountdown;
    private javax.swing.JTextField txtEndText;
    private javax.swing.JFormattedTextField txtTimer;
    // End of variables declaration//GEN-END:variables
}
